name: docs_page
description: Docs.page CLI package
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.3.0
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  path: ^1.8.1
  toml: "^0.12.0"
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner:

executables:
  docs_page: 

repository: https://github.com/invertase/docs.page